sonar.projectKey=streamflix-clone
sonar.projectName=StreamFlix Clone
sonar.sources=app/src
sonar.exclusions=app/node_modules/**,app/dist/**
sonar.tests=app/src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js
sonar.sourceEncoding=UTF-8
